export const ACTION_META: Record<string, { category: string; severity: string }> = {
  AUTH_LOGIN: { category: "authentication", severity: "info" },
  AUTH_LOGIN_FAILED: { category: "authentication", severity: "warning" },
  AUTH_LOGOUT: { category: "authentication", severity: "info" },
  MFA_ENABLED: { category: "mfa", severity: "info" },
  MFA_VERIFIED: { category: "mfa", severity: "info" },
  MFA_VERIFY_FAILED: { category: "mfa", severity: "warning" },
  MFA_RESET_INITIATED: { category: "mfa", severity: "warning" },
  MFA_RESET_COMPLETED: { category: "mfa", severity: "info" },
  MFA_ADMIN_RESET: { category: "mfa", severity: "critical" },
  PASSWORD_CHANGED: { category: "password", severity: "info" },
  PASSWORD_RESET_REQUESTED: { category: "password", severity: "warning" },
  PASSWORD_RESET_COMPLETED: { category: "password", severity: "info" },
  PASSWORD_ADMIN_RESET: { category: "password", severity: "critical" },
  USER_REGISTERED: { category: "user_management", severity: "info" },
  USER_CREATED: { category: "user_management", severity: "info" },
  USER_UPDATED: { category: "user_management", severity: "info" },
  USER_APPROVED: { category: "user_management", severity: "info" },
  USER_REJECTED: { category: "user_management", severity: "warning" },
  USER_DEACTIVATED: { category: "user_management", severity: "warning" },
  USER_ACTIVATED: { category: "user_management", severity: "info" },
  ROLE_CREATED: { category: "role_management", severity: "info" },
  ROLE_UPDATED: { category: "role_management", severity: "info" },
  ROLE_DELETED: { category: "role_management", severity: "warning" },
  ROLE_ASSIGNED: { category: "role_management", severity: "info" },
  HOSPITAL_CREATED: { category: "organization", severity: "info" },
  HOSPITAL_UPDATED: { category: "organization", severity: "info" },
  CLINIC_CREATED: { category: "organization", severity: "info" },
  CLINIC_UPDATED: { category: "organization", severity: "info" },
  INVITATION_CREATED: { category: "invitation", severity: "info" },
  INVITATION_USED: { category: "invitation", severity: "info" },
  SETTINGS_UPDATED: { category: "settings", severity: "info" },
  BRANDING_UPDATED: { category: "settings", severity: "info" },
  EMAIL_SENT: { category: "email", severity: "info" },
};

export const AUDIT_ACTIONS = Object.keys(ACTION_META);
export const AUDIT_CATEGORIES = [...new Set(Object.values(ACTION_META).map((m) => m.category))];
